### ISSUE TITLE
Requiring via browserify makes window.XMLHttpRequest undefined

### ISSUE THREAD

**Issue by tmcw** [iriscouch/browser-request#21]
``` js
// good
console.log(window.XMLHttpRequest);

var request = require('browser-request');

// undefined
console.log(window.XMLHttpRequest);
```

**Comment by ben-ng** [comment]
Found my way here because this module broke `backbone.sync`.

Is it really necessary to clobber the global?

**Comment by svnm** [comment]
I have the same issue `ReferenceError: XMLHttpRequest is not defined` using Browserify
